import os from 'os';
import copy from 'rollup-plugin-copy';
import typescript from '@rollup/plugin-typescript';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import scss from 'rollup-plugin-scss';

const TEST_VAULT = `${os.homedir()}/Documents/Obsidian/Test Grounds/.obsidian/plugins/banners`;
const isDev = process.env.NODE_ENV === 'dev';

const banner =
`/*
- THIS IS A GENERATED/BUNDLED FILE BY ROLLUP -
Please visit the repository linked to view the source code:
https://github.com/noatpad/obsidian-banners
*/`;

const plugins = [
  typescript(),
  nodeResolve({ browser: true }),
  commonjs(),
  scss({ output: 'dist/styles.css', sass: require('sass') })
];

if (isDev) {
  plugins.push(
    copy({ targets: [{ src: ['dist/**/*', 'manifest.json', '.hotreload'], dest: TEST_VAULT }] })
  );
}

export default {
  input: 'src/main.ts',
  output: {
    dir: 'dist/',
    sourcemap: isDev ? 'inline' : false,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins
};
